"""criar o atributo e-mail na tabela de alunos

Revision ID: bfa7a6305a8e
Revises: f27b05c2c7f4
Create Date: 2026-04-28 14:20:56.889611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfa7a6305a8e'
down_revision: Union[str, Sequence[str], None] = 'f27b05c2c7f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alunos', sa.Column('email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alunos', 'email')
    # ### end Alembic commands ###
