"""criar a restrição de unicidade no atributo e-mail na tabela de alunos

Revision ID: e56f5d185f30
Revises: bfa7a6305a8e
Create Date: 2026-04-28 14:42:58.909638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e56f5d185f30'
down_revision: Union[str, Sequence[str], None] = 'bfa7a6305a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'alunos', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alunos', type_='unique')
    # ### end Alembic commands ###
